2025-08-11 16:19:28 [ERROR] Internal Server Error: /accounts/login/ — C:\Users\Роман\PycharmProjects\PythonProject5\.venv\Lib\site-packages\django\utils\log.py None
Traceback (most recent call last):
  File "C:\Users\Роман\PycharmProjects\PythonProject5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Роман\PycharmProjects\PythonProject5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Роман\PycharmProjects\PythonProject5\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Роман\PycharmProjects\PythonProject5\.venv\Lib\site-packages\django\views\generic\base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Роман\PycharmProjects\PythonProject5\logproj\accounts\views.py", line 79, in get
    return render(request, "login.html", {"form": LoginForm()})
  File "C:\Users\Роман\PycharmProjects\PythonProject5\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Роман\PycharmProjects\PythonProject5\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Роман\PycharmProjects\PythonProject5\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: login.html
2025-08-11 16:19:28 [ERROR] "GET /accounts/login/ HTTP/1.1" 500 101197 — C:\Users\Роман\PycharmProjects\PythonProject5\.venv\Lib\site-packages\django\core\servers\basehttp.py None
2025-08-11 16:20:13 [ERROR] Internal Server Error: /accounts/login/ — C:\Users\Роман\PycharmProjects\PythonProject5\.venv\Lib\site-packages\django\utils\log.py None
Traceback (most recent call last):
  File "C:\Users\Роман\PycharmProjects\PythonProject5\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Роман\PycharmProjects\PythonProject5\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Роман\PycharmProjects\PythonProject5\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Роман\PycharmProjects\PythonProject5\.venv\Lib\site-packages\django\views\generic\base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Роман\PycharmProjects\PythonProject5\logproj\accounts\views.py", line 79, in get
    return render(request, "login.html", {"form": LoginForm()})
  File "C:\Users\Роман\PycharmProjects\PythonProject5\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Роман\PycharmProjects\PythonProject5\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Роман\PycharmProjects\PythonProject5\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: login.html
2025-08-11 16:20:13 [ERROR] "GET /accounts/login/ HTTP/1.1" 500 101197 — C:\Users\Роман\PycharmProjects\PythonProject5\.venv\Lib\site-packages\django\core\servers\basehttp.py None
